name: mesa_news_projeto
description: Projeto Mesa News
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx:
  flutter_mobx:
  http:
  webview_flutter: ^2.0.4
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.2
  connectivity: ^3.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen:
  build_runner:
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "image/mesa_logo.png"

flutter:
  uses-material-design: true
  assets:
    - image/mesa_logo.png
    - image/login_image.png
